---
title: "Qusage: Speeding up VIF in RcppArmadillo"
author:  "Timothy J. Triche, Jr, Anthony R. Colombo"
output: 
    pdf_document:
      toc: true
      number_sections: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

#SpeedSage Intro
qusage is published software that is slow for large runs, SpeedSage corrects for speed and efficiency at large orders.  there is Bottlenecking of Functions
Qusage can improve the speed of its algorithm by minimizing the cost of computaiton.

##changes Armadillo C++ 
trading NA flexibility slows down qusage runs, but having the user input no NAs enforcing good input, this speeds up calcIndividualExpressions, as well as using C++ libraries.

#calcVif Function
This test the local version which enforces no NA in Baseline or PostTreatment object, this reduces the flexibility. this test data is from the vignette where postTreatment was modified to be Baseline+20.4, a simple training set from the QuSAGE vignette.

```{r} 
library(inline)
library(microbenchmark)
library(Rcpp)
library(parallel)
library(speedSage)
library(qusage)
library(ggplot2)
eset<-system.file("extdata","eset.RData",package="speedSage")
load(eset)
labels<-c(rep("t0",134),rep("t1",134))
contrast<-"t1-t0"
colnames(eset)<-c(rep("t0",134),rep("t1",134))
fileISG<-system.file("extdata","c2.cgp.v5.1.symbols.gmt",package="speedSage")
ISG.geneSet<-read.gmt(fileISG)
geneSets<-ISG.geneSet[grepl("DER_IFN_GAMMA_RESPONSE_UP",names(ISG.geneSet))]
Baseline<-eset
PostTreatment<-eset+20.4
ncol(Baseline) #not splitting up eset

sourceCpp(file="/home/anthonycolombo/Documents/qusage/qusage_repos/qusage_speed/R/sigmaArm.cpp")
sourceCpp(file="/home/anthonycolombo/Documents/qusage/qusage_repos/qusage_speed/R/sigmaSingle.cpp")
sourceCpp(file="/home/anthonycolombo/Documents/qusage/qusage_repos/qusage_speed/R/bayesEstimation.cpp")
sourceCpp(file="/home/anthonycolombo/Documents/qusage/qusage_repos/qusage_speed/R/notbayesEstimation.cpp")
sourceCpp(file="/home/anthonycolombo/Documents/qusage/qusage_repos/qusage_speed/R/calcVIFarm.cpp")
sourceCpp(file="/home/anthonycolombo/Documents/qusage/qusage_repos/qusage_speed/R/calcVIFarmalt.cpp")
sourceCpp(file="/home/anthonycolombo/Documents/qusage/qusage_repos/qusage_speed/R/calcVIFarm_nosdalphaalt.cpp")

pairVector<-NULL
var.equal<-FALSE
filter.genes<-FALSE
n.points<-2^12


#setting up calcVif call objects
results = makeComparisonArm(eset, labels, contrast, pairVector=pairVector,var.equal=var.equal)
nu = floor(min(results$dof,na.rm=T))
geneResults = aggregateGeneSet(results, geneSets, silent=F, n.points=n.points)
#eset, and results parameters for vif

useAllData<-TRUE
useCAMERA<-FALSE
##### qusage VIF calc
ogVIF<-calcVIF(eset,geneResults)

#for local code use  
ogGeneSets<-geneResults$pathways
GNames<-names(geneResults$mean)[ogGeneSets[[1]]]
gs.i = which(rownames(eset)%in%GNames)
grps = split(1:ncol(eset),geneResults$labels)
covar.mat = cov(t(eset[gs.i,grps[[1]]])) * (length(grps[[1]])-1)

 if(length(grps)>1){
       for(i in 2:length(grps)){
          covar.mat = covar.mat + ( cov(t(eset[gs.i,grps[[i]]])) * (length(grps[[i]])-1) )
        }
      }
      covar.mat = covar.mat / (ncol(eset) - length(grps))
###original covar.mat

if(!is.null(geneResults$sd.alpha)){
        a = geneResults$sd.alpha[rownames(eset)[gs.i]]
        covar.mat = t(covar.mat*a)*a
      }

      vif = sum(covar.mat)/sum(diag(covar.mat))

original<-list(GNames,gs.i,covar.mat,a , vif)
###now to compare

t<-calcVIFarm(names(geneResults$mean),geneResults$pathways[[1]],rownames(eset),eset,unique(labels), geneResults$sd.alpha)
useCAMERA<-FALSE

t2<-calcVIFarmalt(names(geneResults$mean),gs.i, geneResults$pathways[[i]],rownames(eset),eset,levels(geneResults$labels), geneResults$sd.alpha) 

microbenchmark(
calcVIFarmalt(names(geneResults$mean),gs.i, geneResults$pathways[[i]],rownames(eset),eset,levels(geneResults$labels), geneResults$sd.alpha),
calcVIF(eset,geneResults) )




source("calcVIFArm.R")
myVIF<-calcVIFArm(eset,geneResults)



### TO DO ensure that calcVIFarm matches qusage::calcVIF.R

identical(names(myVIF),names(ogVIF))
identical(myVIF$labels,ogVIF$labels)
 identical(myVIF$contrast,ogVIF$contrast)
identical(myVIF$n.samples,ogVIF$n.samples)
identical(myVIF$mean,ogVIF$mean)
 identical(myVIF$sd.alpha,ogVIF$sd.alpha)
 identical(myVIF$dof,ogVIF$dof)
identical(myVIF$var.method,ogVIF$var.method)
identical(myVIF$pathways,ogVIF$pathways)
identical(myVIF$path.mean,ogVIF$path.mean)
 identical(myVIF$path.size,ogVIF$path.size)
identical(myVIF$ranges,ogVIF$ranges)
 identical(myVIF$n.points,ogVIF$n.points)
all.equal(myVIF$path.PDF,ogVIF$path.PDF)
all.equal(myVIF$vif,ogVIF$vif)


qplot( as.vector(abs(myVIF$path.PDF-ogVIF$path.PDF)), xlab="Path PDF ") 

qplot( as.vector(abs(myVIF$vif-ogVIF$vif)), xlab="VIF ")


mb<-microbenchmark(
myVIF<-calcVIFArm(eset,geneResults),
ogVIF<-calcVIF(eset,geneResults) )

mb

require(profr)
require(ggplot2)
x1<-profr(calcVIFArm(eset,geneResults))
x2<-profr(calcVIFarm(names(geneResults$mean),geneResults$pathways[[1]],rownames(eset),eset,unique(labels), geneResults$sd.alpha))
ggplot(x1)
ggplot(x2)
