#' Filter out genes with SD lower than a threshold and mean lower than another threshold
#' @param QSarray A QSarray object, as generated by makeComparison 
#' @param Min_SD threshold for SD
#' @param Min_Mean threshold for mean
#' @export 
#' @return qsuage array object filtered
filterGenes<-function(QSarray,  ##A QSarray object, as generated by makeComparison 
                      Min_SD=0.01, ##threshold  for SD
                      Min_Mean=0   ##threshold  for mean
                     ){

 if(!is.null(QSarray$pathways)){stop("too late...aggregateGeneSet already being called")}

 Indexes <- abs(QSarray$mean) >= Min_Mean | QSarray$SD >= Min_SD

 QSarray$mean <- QSarray$mean[Indexes]
 QSarray$SD <- QSarray$SD[Indexes]
 QSarray$dof <- QSarray$dof[Indexes]
 QSarray$sd.alpha <- QSarray$sd.alpha[Indexes]

 return(QSarray)
}

